apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Chart.Name }}-http-service
  namespace: {{ lower .Chart.Name }}
  {{- if .Values.horde.service.http.annotations }}
  annotations:
    {{- with .Values.horde.service.http.annotations }}
      {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.horde.service.http.labels }}
  labels:
    {{- with .Values.horde.service.http.labels }}
      {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.horde.service.http.type }}
  selector:
    app: {{ lower .Chart.Name }}-app
  ports:
    - name: {{ lower .Chart.Name }}-http
      protocol: TCP
      port: {{ .Values.horde.service.http.port }}
      targetPort: {{ lower .Chart.Name }}-http-port