{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ lower .Chart.Name }}-ingress
  namespace: {{ lower .Chart.Name }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.labels }}
    labels:
      {{- with .Values.ingress.labels }}
        {{ toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- with .Values.ingress.rules }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}