{{- $name := .Chart.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower $name }}-app
  namespace: {{ lower $name }}
  labels:
    app.kubernetes.io/name: {{ lower $name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ lower $name }}-app
  template:
    metadata:
      labels:
        app: {{ lower $name }}-app
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- else }}
      serviceAccountName: {{ lower $name }}-service-account
      {{- end }}
      volumes:
        - name: shared-data
          emptyDir: { }
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- if .Values.container.resources }}
            {{- with .Values.container.resources }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
          {{- end }}
          ports:
            - name: {{ lower $name }}-http-port
              containerPort: {{ .Values.service.http.port }}
            - name: {{ lower $name }}-grpc-port
              containerPort: {{ .Values.service.grpc.port }}
          volumeMounts:
            - name: shared-data
              mountPath: /app/config
          envFrom:
            - configMapRef:
                name: {{ lower $name }}-configmap
            - configMapRef:
                name: {{ lower $name }}-p4-configmap
            - secretRef:
                name: {{ lower $name }}-p4-secret
            - secretRef:
                name: {{ lower $name }}-mongodb-secret
            {{- range .Values.container.envFromConfigMaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.container.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          env:
            - name: Horde__redisConnectionConfig
              value: {{ .Values.redis.host }}:{{ .Values.redis.port }}
            {{- if .Values.mongodb.install_documentdb_cert }}
            - name: Horde__databasePublicCert
              value: "/app/config/global-bundle.pem"
            {{- end }}
            {{- range .Values.container.env }}
            - {{ .name }}: {{ .value }}
            {{- end }}
      initContainers:
        - name: unreal-horde-p4-trust
          image: ubuntu:noble
          command: ["/bin/sh", "-c"]
          args:
            - |  
              apt-get update
              apt-get install -y curl gnupg
              curl -fs https://package.perforce.com/perforce.pubkey | gpg --dearmor -o /usr/share/keyrings/perforce.gpg
              echo "deb [signed-by=/usr/share/keyrings/perforce.gpg] https://package.perforce.com/apt/ubuntu noble release" > /etc/apt/sources.list.d/perforce.list
              apt-get update
              apt-get install -y p4-cli
              {{- range .Values.perforce.trust_servers }}
              echo "Trusting P4 server {{ . }}"
              p4 -p {{ . }} trust -y
              {{- end }}
          envFrom:
            - configMapRef:
                name: {{ lower $name }}-p4-configmap
            - secretRef:
                name: {{ lower $name }}-p4-secret
          volumeMounts:
            - name: shared-data
              mountPath: /app/config
        {{- if .Values.mongodb.install_documentdb_cert }}
        - name: unreal-horde-docdb-cert
          image: public.ecr.aws/docker/library/bash:5.3
          command: ["wget", "https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem", "-P", "/app/config/"]
          volumeMounts:
            - name: shared-data
              mountPath: /app/config
        {{- end }}