apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Chart.Name }}
data:
  # possible values: ["Anonymous", "Okta", "OpenIdConnect", "Horde"]
  Horde__authMethod: "{{ .Values.auth.authMethod }}"
  Horde__oidcAuthority: "{{ .Values.auth.oidcAuthority }}"
  Horde__oidcAudience: "{{ .Values.auth.oidcAudience }}"
  Horde__oidcClientId: "{{ .Values.auth.oidcClientId }}"
  Horde__oidcClientSecret: "{{ .Values.auth.oidcClientSecret }}"
  Horde__oidcSigninRedirect: "{{ .Values.auth.oidcSigninRedirect }}"
  Horde__adminClaimType: "{{ .Values.auth.adminClaimType }}"
  Horde__adminClaimValue: "{{ .Values.auth.adminClaimValue }}"
  Horde__enableNewAgentsByDefault: "true"
  Horde__Perforce__0__ServerAndPort: "{{ .Values.perforce.server }}"
  Horde__jwtIssuer: "{{ .Values.fully_qualified_domain_name }}"
  Horde__configPath: "{{ .Values.configPath }}"
  ASPNETCORE_ENVIRONMENT: "{{ .Values.environment }}"