apiVersion: v1
kind: Service
{{- $service := .Values.horde.service.grpc | default dict }}
metadata:
  name: {{ lower .Chart.Name }}-grpc-service
  namespace: {{ lower .Chart.Name }}
  {{- if $service.annotations }}
  annotations:
    {{- with $service.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $service.labels }}
  labels:
    {{- with $service.labels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $service.type | default "LoadBalancer" }}
  selector:
    app: {{ lower .Chart.Name }}-app
  ports:
    - name: {{ lower .Chart.Name }}-grpc
      protocol: TCP
      port: {{ $service.port | default 5002 }}
      targetPort: {{ lower .Chart.Name }}-grpc-port