apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Chart.Name }}-service
  namespace: {{ lower .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ lower .Chart.Name }}-app
  ports:
    - name: {{ lower .Chart.Name }}-http
      protocol: TCP
      port: {{ .Values.horde.service.ports.http }}
      targetPort: {{ lower .Chart.Name }}-http-port
    - name: {{ lower .Chart.Name }}-grpc
      protocol: TCP
      port: {{ .Values.horde.service.ports.grpc }}
      targetPort: {{ lower .Chart.Name }}-grpc-port