apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Chart.Name }}-http-service
  namespace: {{ lower .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ lower .Chart.Name }}
  ports:
    - name: {{ lower .Chart.Name }}-api
      port: {{ .Values.horde.service.ports.api }}
      targetPort: {{ lower .Chart.Name }}-api-port
    - name: {{ lower .Chart.Name }}-grpc
      port: {{ .Values.horde.service.ports.grpc }}
      targetPort: {{ lower .Chart.Name }}-grpc-port