apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-p4-secret
  namespace: {{ .Chart.Name }}
data:
  Horde__Perforce__0__credentials__username: {{ .Values.perforce.username | b64enc | quote }}
  Horde__Perforce__0__credentials__password: {{ .Values.perforce.password | b64enc | quote }}
  P4USER: {{ .Values.perforce.username | b64enc | quote }}
  P4PASSWORD: {{ .Values.perforce.password | b64enc | quote }}